### ISSUE TITLE
Add Folders for recipes

### ISSUE THREAD

**Issue by Tann2019** [jlucaspains/sharp-cooking-web#163]
Giving the User the ability to create folders and move existing and new recipes into said folders would allow users with extensive recipe lists the ability to categorize down and make the interface less cluttered and organized.

- [x] User Should be able to create a folder
- [ ] (optional) Folders have the ability to have different colors applied to them
- [x] User can move existing recipes into a new folder.
- [x] user can create a recipe when in a folder and have it automatically populate there

**Comment by jlucaspains** [comment]
@Tann2019, could you use the preview version above and provide some feedback? The current version is not final, but, it should be a good start.

**Comment by Tann2019** [comment]
@jlucaspains, Yeah for sure, I'll give it a whirl!

**Comment by Tann2019** [comment]
@jlucaspains First impressions on #368 is great! A few of my observations may be from the start of the feature and just not implemented yet.

- It would be cool to see the number of recipes in a category, maybe like a notification counter style.
- Able to see empty categories would be great for user experience, that way when they enter the category they can quickly add to it by adding a recipe and having it default to the category they were in.
- A couple of small bugs that I am sure you are aware of -
   - When making a new recipe the category field is blank, not "Select Category".
   - Images Don't work - just a placeholder for right now, but the image does not fit correctly after creating the category and going back to the home page.

These are just my thoughts on the initial run-through, I'll take a look at the PR possibly tomorrow or sometime this week if you want 😊. Looking great!

**Comment by jlucaspains** [comment]
Thanks for testing @Tann2019. Here are my notes about your suggestions:

1. Nice suggestion. I will implement it.
2. I thought about that but wasn't sure if it would be good. Maybe we can use a toggle in the options?
3. See below:
   1.  Good catch. I will fix it.
   2. Are you running the app locally? I took the lazy route of not setting up the image parser locally. If you use the link in the PR, that one works correctly.
   3. Yep. Just WIP. However, I did consider making categories immutable.

thanks for the feedback!

**Comment by Tann2019** [comment]
A toggle would be great! I was running locally since I still had the repo pulled down. Excited to see more of what's to come!

**Comment by jlucaspains** [comment]
I got some of the changes done.

1. The count of recipes in the category was added.
2. I didn't change this yet.
3. See below:
   1. Fixed
   2. No issue
   3. Fixed

**Comment by Tann2019** [comment]
Nice Nice, I noticed the localization for the edit button isn't there yet, 
<img width="282" alt="Screenshot 2024-12-01 at 8 03 38 PM" src="https://github.com/user-attachments/assets/e1f132c5-6d22-42ed-8238-5eb1b796cf13">

Also, the Image parser does take a minute to upload the image sometimes, especially if its big, maybe a spinner would help show that its working, since I tried to upload and image, it wasn't doing anything, then I created it without an image and went to create another one, and the image I was uploading popped up there.

Getting close to closing this up! May be Blog Post worthy 👀

**Comment by jlucaspains** [comment]
@Tann2019 I think I handled everything now. I'm about to generate a preview version. Any last feedback in the PR?

**Comment by Tann2019** [comment]
@jlucaspains I can check in a bit when I get home :) 

I didn't see anything when I initially looked through the PR a while ago, but I can give it another quick glance and test for ya!

**Comment by Tann2019** [comment]
@jlucaspains looks good!

**Comment by jlucaspains** [comment]
@Tann2019 this feature is now available in the PROD version of the app. You will need to enable it on the preview pages to see the categories. I'm calling the version 2.0.0 preview since this is a rather large change. Please create a new issue if you notice problems?
