### ISSUE TITLE
Tried a couple things adding recipes but failed

### ISSUE THREAD

**Issue by Allann** [jlucaspains/sharp-cooking-web#270]
Hoping the app logs errors, I tried 2 main things:
- import recipe from website.  just got a failed message but no detail
- then tried applying an avif image as the hero image and it also failed.

This was the recipe I tried to import:  www.hellofresh.com.au/recipes/chicken-creamy-peppercorn-sauce-6596342ab6e284551035bfb2

**Comment by jlucaspains** [comment]
1. It seems like hellofresh.com.au is not supported by the scraper used in the API side. Here is a list of all supported websites: https://github.com/hhursev/recipe-scrapers. That said, I will look into making a contribution that adds hellofresh.com.au to their list. Also, I will make the return message more clear. Something along the lines of "This webside is not supported".
2. I just checked and the underlying image compressor used doesn't support AVIF files (Pillow). However, there is a plugin to add the support while the main project doesn't add it. I will look into adding the plugin.

**Comment by jlucaspains** [comment]
The problem with loading hellofresh recipes is much wider than anticipated. None of the hellofresh websites work at all. My 4 minute investigation points that the page is no longer server side generated. That is causing the first HTML load to not contain the recipe at all.

**Comment by jlucaspains** [comment]
@Allann I think I got a fix for the avif support.

1. PR containing the change is #273 
2. You can try the fix in the staging website here (it will be deleted when the PR is complete): https://delightful-flower-0c3edd710-273.centralus.2.azurestaticapps.net/

**Comment by Allann** [comment]
avif loaded and saved fine.  thanks

**Comment by jlucaspains** [comment]
Cool. I will close the PR and release it after we figure out the other issues.

**Comment by jlucaspains** [comment]
This feature has been released in [v1.9.0](https://github.com/jlucaspains/sharp-cooking-web/releases/tag/v1.9.0)
