### ISSUE TITLE
UX needs tooltips

### ISSUE THREAD

**Issue by Allann** [jlucaspains/sharp-cooking-web#271]
As a new user to the app, I did not know or understand the meaning of the 5 green round buttons.  Is it possible to add text or a tooltip to them?  Or maybe another view mode for new users?

**Comment by jlucaspains** [comment]
That is a good idea. What platform are you using?

**Comment by jlucaspains** [comment]
Created PR #274 to implement this. Please see implementation at staging website: https://delightful-flower-0c3edd710-274.centralus.2.azurestaticapps.net/

**Comment by Allann** [comment]
windows, and I installed locally.

**Comment by jlucaspains** [comment]
This feature has been released in [v1.9.0](https://github.com/jlucaspains/sharp-cooking-web/releases/tag/v1.9.0)
