### ISSUE TITLE
How do I use the app?

### ISSUE THREAD

**Issue by Allann** [jlucaspains/sharp-cooking-web#272]
![image](https://github.com/jlucaspains/sharp-cooking-web/assets/2005474/19945776-8196-4527-abbe-f25554d44b95)
What happens now?  I have steps and ingredients but don't see any of them.

**Comment by jlucaspains** [comment]
Interesting. That usually happens when you just save a recipe without ingredients and steps. Can you describe how you got to that state?

**Comment by jlucaspains** [comment]
Also, does this doc help? https://sharpcooking.net/web/create/

**Comment by Allann** [comment]
All i did was manuualy copy each line from the website into the recipe.  then saved, no errors presented.  even when I went back to edit it loaded fine with the previous details.  I didn't add a hero image.

![image](https://github.com/jlucaspains/sharp-cooking-web/assets/2005474/73b50fb5-dd32-4800-8e1b-5a8b36df7f8b)

**Comment by jlucaspains** [comment]
Ok. This is extra weird. I copied the same recipe and didn't get the issue. Can you please check developer tools (F12)? Also, even though the recipe doesn't show, can you please share it as a file and drop it here? I will troubleshoot further.

**Comment by jlucaspains** [comment]
@Allann any luck?

**Comment by Allann** [comment]
Sorry, been busy at work, will try check tonight.

**Comment by jlucaspains** [comment]
@Allann I will close this for now. We can resume work on it later if needed.
